image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'dotnet build devspace2.sln'
    command: 'dotnet run devspace2.csproj'

vscode:
  extensions:
#    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
    - muhammad-sammy.csharp@1.23.4:1786ec879bdf1fc2fb25016465d0ee1c